[workspace]

members = [
    "blake2",
    "bls12pairing",
    "ecadd",
    "ecmul",
    "ecpairing",
    "ed25519",
    "identity",
    "keccak256",
    "ripemd160",
    "sha1",
    "sha256",
]

[profile.release]
lto = true
