[package]
name = "ewasm-precompile-bls12pairing"
version = "0.1.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
repository = "https://github.com/ewasm/ewasm-precompiles"
description = "Ethereum BLS12-381 pairing precompile in Rust"
publish = false

[dependencies]
ewasm_api = { git = "https://github.com/ewasm/ewasm-rust-api", tag = "0.2.0" }
pairing = { git = "https://github.com/zkcrypto/pairing" }
rand = "0.4"

[lib]
crate-type = ["cdylib"]
